version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: proxy
    depends_on:
      - web
      - api
  web:
    #image: frontend-web
    build:
        context: .
        dockerfile: Admin/Dockerfile
    expose:
      - 80
  api:
    #image: backapi:latest
    build:
        context: .
        dockerfile: DockerASPNetCore/Dockerfile
    ports:
      - 8080:80
